openapi: 3.0.1
info:
  title: '@jupiterone/graph-cycognito'
  description: A JupiterOne Integration for ingesting data of CyCognito
  x-cortex-git:
    github:
      repository: JupiterOne/graph-cycognito
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-cycognito'
  x-cortex-service-groups:
    - tier-4
